"""add patient column

Revision ID: 4b75c9b7b576
Revises: a8cfacd304b4
Create Date: 2025-01-11 19:34:06.555889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b75c9b7b576'
down_revision = 'a8cfacd304b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_pdf', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('report_pdf')

    # ### end Alembic commands ###
