"""Add age, gender, and phone number to Patient

Revision ID: 683f9badb555
Revises: 4b75c9b7b576
Create Date: 2025-01-17 12:33:03.340700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683f9badb555'
down_revision = '4b75c9b7b576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
