"""Added brain_image to Patient model

Revision ID: ba0e4217d0ec
Revises: 683f9badb555
Create Date: 2025-04-17 23:19:02.257302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0e4217d0ec'
down_revision = '683f9badb555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brain_mri_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('brain_mri_image')

    # ### end Alembic commands ###
