"""Add tumor_stage column

Revision ID: d07963a0f778
Revises: c891e3c2e4bd
Create Date: 2024-12-14 15:36:40.164675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07963a0f778'
down_revision = 'c891e3c2e4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tumor_stage', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('tumor_stage')

    # ### end Alembic commands ###
