"""Add brain_report_pdf field to Patient model

Revision ID: f40becc31891
Revises: c35cba7d2402
Create Date: 2025-04-18 21:29:06.651701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40becc31891'
down_revision = 'c35cba7d2402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brain_report_pdf', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('brain_report_pdf')

    # ### end Alembic commands ###
