"""Add biopsy_file column

Revision ID: f4b08c00b9d2
Revises: d07963a0f778
Create Date: 2024-12-15 13:03:41.126322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b08c00b9d2'
down_revision = 'd07963a0f778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biopsy_file', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('biopsy_file')

    # ### end Alembic commands ###
